# analysis_tab.py

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font, NamedStyle
from openpyxl.utils.dataframe import dataframe_to_rows
from io import BytesIO
import streamlit as st
import pandas as pd

from finance.data_fetcher import fetch_financial_statements
from finance.analysis.analysis_tables.analysis_table_income import build_income_analysis_table
from finance.analysis.analysis_tables.analysis_table_balance import build_balance_analysis_table
from finance.analysis.analysis_tables.analysis_table_cashflow import build_cashflow_analysis_table
from finance.analysis.analysis_tables.analysis_table_extended import build_extended_analysis_table


# Dictionary for metric descriptions
metrics_description = {
    "Revenue ($)": "Total income generated by a company from its core business operations, representing its overall sales performance.",
    "Gross-Profit ($)": "The earnings remaining after subtracting the direct costs of goods or services sold, indicating production efficiency.",
    "Gross-Profit-Margin (%)": "The percentage of revenue retained as profit after accounting for direct costs, measuring profitability from core activities.",
    "EBIT ($)": "Earnings before interest and taxes, reflecting operational profitability without considering financing costs.",
    "EBIT Margin (%)": "The proportion of revenue that remains as operating profit, showing operational efficiency.",
    "Interest Coverage Ratio (#)": "A measure of the company’s ability to pay interest on its debt with its operating income.",
    "Net Income ($)": "The company’s total profit after all expenses, taxes, and interest have been deducted, reflecting overall profitability.",
    "Net Income Margin (%)": "The percentage of revenue that turns into net profit, indicating how effectively a company converts sales into earnings.",
    "R&D to Revenue Ratio (%)": "The proportion of revenue spent on research and development, showing investment in innovation.",
    "Personnel Expense (%)": "The percentage of revenue allocated to employee-related costs, reflecting the cost structure related to labor.",
    "Current Assets (€)": "Assets that can be converted to cash or used within one year, indicating short-term liquidity.",
    "Total Assets (€)": "The total value of everything the company owns, including both current and long-term assets.",
    "Current Liabilities (€)": "Short-term obligations that must be settled within a year, showing immediate financial commitments.",
    "Total Liabilities (€)": "The total amount of debt and obligations the company owes, including both short and long-term liabilities.",
    "Working Capital (€)": "The difference between current assets and current liabilities, indicating short-term financial health.",
    "Current Ratio (#)": "A liquidity ratio measuring the ability to cover short-term obligations with short-term assets.",
    "Equity (€)": "The net value attributable to shareholders, representing the ownership stake in the company.",
    "Return on Equity (%)": "A measure of profitability showing how effectively equity is used to generate earnings.",
    "Equity Ratio (%)": "The proportion of total assets financed by shareholders' equity, indicating financial stability.",
    "Debt Ratio (Gearing) (%)": "The proportion of a company’s debt relative to its equity, reflecting leverage.",
    "Dividends (€)": "Cash distributions paid to shareholders from company earnings, representing a share of profit.",
    "Dividends to Share (%)": "The percentage of earnings paid to shareholders as dividends per share.",
    "Operating Cashflow (€)": "Cash generated from regular business operations, indicating the company’s ability to maintain and grow its activities.",
    "Operating Cashflow Margin (%)": "The efficiency with which revenue is converted into cash from operations, measuring liquidity.",
    "Market Cap ($)": "The total market value of the company’s outstanding shares, indicating its size and valuation.",
    "Trailing P/E": "The price-to-earnings ratio based on the last twelve months of earnings, used to assess valuation.",
    "Forward P/E": "The projected price-to-earnings ratio, reflecting expectations of future profitability.",
    "Price to Book": "The ratio of market value to book value, showing how investors value the company relative to its net assets.",
    "Price to Sales (TTM)": "The ratio of a company’s stock price to its revenue per share, indicating valuation relative to sales.",
    "Current Price ($)": "The most recent market price of the company’s stock, reflecting current investor sentiment.",
    "52-Week High ($)": "The highest stock price recorded over the last year, showing peak investor valuation.",
    "52-Week Low ($)": "The lowest stock price recorded over the last year, indicating minimum investor valuation.",
    "Volume": "The number of shares traded during a specific period, reflecting market activity and liquidity."
}


def show_analysis_tab(selected_ticker):
    """
    Fetches and displays financial analysis tables and provides an option to download all tables as a single Excel file
    with enhanced formatting.
    """
    st.title("Analysis Overview")

    # Sidebar: Dropdown for metric selection
    st.sidebar.header("Metric Description")
    selected_metric = st.sidebar.selectbox("Select a metric to view its description:", list(metrics_description.keys()))

    # Display metric description in the sidebar
    if selected_metric:
        st.sidebar.subheader(f"Description of {selected_metric}")
        st.sidebar.write(metrics_description[selected_metric])

    # Fetch data
    balance_df, income_df, cashflow_df, info = fetch_financial_statements(selected_ticker)

    # Initialize a list to hold all tables for concatenation
    all_tables = []

    # Income Statement Analysis
    st.subheader("Income Statement")
    if income_df is not None and not income_df.empty:
        displayed_income_df = build_income_analysis_table(income_df)
        all_tables.append(displayed_income_df)

    # Balance Sheet Analysis
    st.subheader("Balance Sheet")
    if balance_df is not None and not balance_df.empty:
        displayed_balance_df = build_balance_analysis_table(balance_df, income_df)
        all_tables.append(displayed_balance_df)

    # Cash Flow Analysis
    st.subheader("Cash Flow")
    if cashflow_df is not None and not cashflow_df.empty:
        displayed_cashFlow_df = build_cashflow_analysis_table(cashflow_df, income_df)
        all_tables.append(displayed_cashFlow_df)

    # Extended Values
    st.subheader("General Values")
    if cashflow_df is not None and not cashflow_df.empty:
        displayed_extValues_df = build_extended_analysis_table(info)

        # Move "Value" column into the "Latest Value" column for consistency
        if "Value" in displayed_extValues_df.columns:
            displayed_extValues_df = displayed_extValues_df.rename(columns={"Value": "Latest Value"})

        all_tables.append(displayed_extValues_df)

    # Only create an Excel download if we have data
    if all_tables:
        # 1. Combine tables
        combined_df = pd.concat(all_tables, ignore_index=True)
        # 2. Remove any color columns if they exist
        combined_df = combined_df.loc[:, ~combined_df.columns.str.contains("color", case=False)]

        # 3. Create a new workbook and select the active sheet
        wb = Workbook()
        ws = wb.active
        ws.title = "Analysis Overview"

        # 4. Define NamedStyles
        currency_style = NamedStyle(name="currency_style", number_format="$#,##0.00")
        euro_currency_style = NamedStyle(name="euro_currency_style", number_format="€#,##0.00")
        percentage_style = NamedStyle(name="percentage_style", number_format="0.00%")

        # 5. Collect existing style names safely
        existing_style_names = set()
        for s in wb.named_styles:
            if isinstance(s, NamedStyle):
                existing_style_names.add(s.name)
            elif isinstance(s, str):
                existing_style_names.add(s)

        # 6. Add our styles if they aren't already present
        for style in [currency_style, euro_currency_style, percentage_style]:
            if style.name not in existing_style_names:
                wb.add_named_style(style)

        # 7. Write the DataFrame to the Excel sheet (headers + data)
        for r_idx, row in enumerate(dataframe_to_rows(combined_df, index=False, header=True), start=1):
            for c_idx, value in enumerate(row, start=1):
                ws.cell(row=r_idx, column=c_idx, value=value)

        # 8. Apply formatting (fonts/alignments) to the header row
        header_font = Font(bold=True)
        header_alignment = Alignment(horizontal="center", vertical="center")
        for cell in ws[1]:
            cell.font = header_font
            cell.alignment = header_alignment

        # 9. For data rows, adjust styles if header indicates '%', '$', or '€'
        #    (start at row=2 so we skip the header)
        max_col = ws.max_column
        max_row = ws.max_row

        for row in ws.iter_rows(min_row=2, max_row=max_row, min_col=1, max_col=max_col):
            for cell in row:
                if cell.value is None:
                    continue  # skip empty cells

                # Check the column header
                col_header = ws.cell(row=1, column=cell.column).value

                # If this column is a percentage
                if isinstance(cell.value, (int, float)) and '%' in str(col_header):
                    # e.g. 25 instead of 0.25 => fix it
                    cell.value = cell.value / 100.0
                    cell.style = percentage_style

                # If this column is USD
                elif isinstance(cell.value, (int, float)) and '$' in str(col_header):
                    cell.style = currency_style

                # If this column is EUR
                elif isinstance(cell.value, (int, float)) and '€' in str(col_header):
                    cell.style = euro_currency_style

                # Otherwise, leave as default

        # 10. Save the workbook to a BytesIO stream
        output = BytesIO()
        wb.save(output)
        output.seek(0)

        # 11. Provide the download button
        st.download_button(
            label="Download Analysis as Excel",
            data=output,
            file_name=f"{selected_ticker}_analysis_combined.xlsx",
            mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
        )
    else:
        st.warning("No data available to download.")
