# analysis_tab.py

import streamlit as st

from finance.data_fetcher import fetch_financial_statements
from finance.analysis.analysis_tables.analysis_table_income import build_income_analysis_table
from finance.analysis.analysis_tables.analysis_table_balance import build_balance_analysis_table
from finance.analysis.analysis_tables.analysis_table_cashflow import build_cashflow_analysis_table
from finance.analysis.analysis_tables.analysis_table_extended import build_extended_analysis_table


# Dictionary for metric descriptions
metrics_description = {
    "Revenue ($)": "Total income generated by a company from its core business operations, representing its overall sales performance.",
    "Gross-Profit ($)": "The earnings remaining after subtracting the direct costs of goods or services sold, indicating production efficiency.",
    "Gross-Profit-Margin (%)": "The percentage of revenue retained as profit after accounting for direct costs, measuring profitability from core activities.",
    "EBIT ($)": "Earnings before interest and taxes, reflecting operational profitability without considering financing costs.",
    "EBIT Margin (%)": "The proportion of revenue that remains as operating profit, showing operational efficiency.",
    "Interest Coverage Ratio (#)": "A measure of the company’s ability to pay interest on its debt with its operating income.",
    "Net Income ($)": "The company’s total profit after all expenses, taxes, and interest have been deducted, reflecting overall profitability.",
    "Net Income Margin (%)": "The percentage of revenue that turns into net profit, indicating how effectively a company converts sales into earnings.",
    "R&D to Revenue Ratio (%)": "The proportion of revenue spent on research and development, showing investment in innovation.",
    "Personnel Expense (%)": "The percentage of revenue allocated to employee-related costs, reflecting the cost structure related to labor.",
    "Current Assets (€)": "Assets that can be converted to cash or used within one year, indicating short-term liquidity.",
    "Total Assets (€)": "The total value of everything the company owns, including both current and long-term assets.",
    "Current Liabilities (€)": "Short-term obligations that must be settled within a year, showing immediate financial commitments.",
    "Total Liabilities (€)": "The total amount of debt and obligations the company owes, including both short and long-term liabilities.",
    "Working Capital (€)": "The difference between current assets and current liabilities, indicating short-term financial health.",
    "Current Ratio (#)": "A liquidity ratio measuring the ability to cover short-term obligations with short-term assets.",
    "Equity (€)": "The net value attributable to shareholders, representing the ownership stake in the company.",
    "Return on Equity (%)": "A measure of profitability showing how effectively equity is used to generate earnings.",
    "Equity Ratio (%)": "The proportion of total assets financed by shareholders' equity, indicating financial stability.",
    "Debt Ratio (Gearing) (%)": "The proportion of a company’s debt relative to its equity, reflecting leverage.",
    "Dividends (€)": "Cash distributions paid to shareholders from company earnings, representing a share of profit.",
    "Dividends to Share (%)": "The percentage of earnings paid to shareholders as dividends per share.",
    "Operating Cashflow (€)": "Cash generated from regular business operations, indicating the company’s ability to maintain and grow its activities.",
    "Operating Cashflow Margin (%)": "The efficiency with which revenue is converted into cash from operations, measuring liquidity.",
    "Market Cap ($)": "The total market value of the company’s outstanding shares, indicating its size and valuation.",
    "Trailing P/E": "The price-to-earnings ratio based on the last twelve months of earnings, used to assess valuation.",
    "Forward P/E": "The projected price-to-earnings ratio, reflecting expectations of future profitability.",
    "Price to Book": "The ratio of market value to book value, showing how investors value the company relative to its net assets.",
    "Price to Sales (TTM)": "The ratio of a company’s stock price to its revenue per share, indicating valuation relative to sales.",
    "Current Price ($)": "The most recent market price of the company’s stock, reflecting current investor sentiment.",
    "52-Week High ($)": "The highest stock price recorded over the last year, showing peak investor valuation.",
    "52-Week Low ($)": "The lowest stock price recorded over the last year, indicating minimum investor valuation.",
    "Volume": "The number of shares traded during a specific period, reflecting market activity and liquidity."
}


def show_analysis_tab(selected_ticker):
    """
    High-level function that:
    1) Fetches the 3 dataframes for the selected ticker (Income, Balance, Cashflow).
    2) Builds and displays an analysis table for each statement.
    """

    st.title("Analysis Overview")

    # Sidebar: Dropdown for metric selection
    st.sidebar.header("Metric Description")
    selected_metric = st.sidebar.selectbox("Select a metric to view its description:", list(metrics_description.keys()))

    # Display metric description in the sidebar
    if selected_metric:
        st.sidebar.subheader(f"Description of {selected_metric}")
        st.sidebar.write(metrics_description[selected_metric])

    # 1) Fetch data
    balance_df, income_df, cashflow_df, info = fetch_financial_statements(selected_ticker)

    # 2) Income Statement Analysis
    st.subheader("Income Statement")
    if income_df is None or income_df.empty:
        st.warning("No income statement data found.")
    else:
        build_income_analysis_table(income_df)

    # 3) Balance Sheet Analysis
    st.subheader("Balance Sheet")
    if balance_df is None or balance_df.empty:
        st.warning("No balance sheet data found.")
    else:
        build_balance_analysis_table(balance_df, income_df)

    # 4) Cash Flow Analysis
    st.subheader("Cash Flow")
    if cashflow_df is None or cashflow_df.empty:
        st.warning("No cashflow data found.")
    else:
        build_cashflow_analysis_table(cashflow_df, income_df)

    # 5) Extended values
    st.subheader("General values")
    if cashflow_df is None or cashflow_df.empty:
        st.warning("No cashflow data found.")
    else:
        build_extended_analysis_table(info)
